name: Build OpenVPNAdapter for ios

on: [push]

jobs:
  build-macos:
    name: 'AmneziaWG for macOS NE'
    runs-on: macos-latest
    if: |
      contains(github.event.head_commit.message, '[all]') ||
      contains(github.event.head_commit.message, '[macos]') ||
      contains(github.event.head_commit.message, '[openvpnadapter]')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 'Get OpenVPNAdapter'
        uses: actions/checkout@v3
        with:
          repository: amnezia-vpn/OpenVPNAdapter
          ref: feature/macox-network-extension
          path: OpenVPNAdapter

      - name: Set up Xcode environment
        run: |
          echo "Setting up Xcode environment"
          export XCODEBUILD="/usr/bin/xcodebuild"
          export WORKINGDIR=`pwd`
          export PATCH="/usr/bin/patch"
          echo "Working directory: $WORKINGDIR"

      - name: Configure amnezia.xcconfig
        run: |
          echo "Configuring amnezia.xcconfig..."
          cat $WORKINGDIR/OpenVPNAdapter/Configuration/Project-MacNE.xcconfig > $WORKINGDIR/OpenVPNAdapter/Configuration/amnezia.xcconfig
          cat << EOF >> $WORKINGDIR/OpenVPNAdapter/Configuration/amnezia.xcconfig
          PROJECT_TEMP_DIR = $WORKINGDIR/OpenVPNAdapter/build/OpenVPNAdapter.build
          CONFIGURATION_BUILD_DIR = $WORKINGDIR/OpenVPNAdapter/build/Release-macos
          BUILT_PRODUCTS_DIR = $WORKINGDIR/OpenVPNAdapter/build/Release-macos
          EOF

      - name: Get macOS SDK 
        id: sdk_version
        run: |
          MACOSX_SDK=$(xcrun --sdk macosx --show-sdk-path | sed -E 's/.*MacOSX([0-9]+\.[0-9]+)\.sdk/\1/')
          echo "Using macOS SDK version: $MACOSX_SDK"
          echo "::set-output name=sdk::$MACOSX_SDK"

      - name: Build OpenVPNAdapter
        run: |
          cd OpenVPNAdapter
          $XCODEBUILD -scheme OpenVPNAdapter \
            -configuration Release \
            -xcconfig Configuration/amnezia.xcconfig \
            -sdk macosx${{ steps.sdk_version.outputs.sdk }} \
            -destination 'generic/platform=macOS' \
            -project OpenVPNAdapter.xcodeproj

      - name: Remove CodeSignature
        run: |
          echo "Removing CodeSignature if exists..."
          rm -rf ./build/Release-macos/OpenVPNAdapter.framework/Versions/A/_CodeSignature

      - name: Archive Build
        uses: actions/upload-artifact@v3
        with:
          name: OpenVPNAdapter-macos
          path: OpenVPNAdapter/build/Release-macos
